### ISSUE TITLE
Loading file raises a pymatreader error

### ISSUE THREAD

**Issue by S73ph4n** [ctroein/octavvs#6]
When trying to open any .mat file, I get :

`TypeError("__init__() got an unexpected keyword argument 'uint16_codec'")`
Here is the whole traceback :
> Traceback (most recent call last):
>   File "/home/stephan/Documents/Education/Lund_University/FYTM04/octavvs/octavvs/ui/fileloader.py", line 132, in loadFile
>     self.data.read_matrix(file)
>   File "/home/stephan/Documents/Education/Lund_University/FYTM04/octavvs/octavvs/io/spectraldata.py", line 63, in read_matrix
>     s = read_mat(filename)
>   File "/usr/lib/python3.8/site-packages/pymatreader/pymatreader.py", line 82, in read_mat
>     raw_data = scipy.io.loadmat(fid, struct_as_record=True,
>   File "/usr/lib/python3.8/site-packages/scipy/io/matlab/mio.py", line 217, in loadmat
>     MR, _ = mat_reader_factory(f, **kwargs)
>   File "/usr/lib/python3.8/site-packages/scipy/io/matlab/mio.py", line 74, in mat_reader_factory
>     return MatFile4Reader(byte_stream, **kwargs), file_opened
>   File "/usr/lib/python3.8/site-packages/scipy/io/matlab/mio4.py", line 313, in __init__
>     super(MatFile4Reader, self).__init__(mat_stream, *args, **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'uint16_codec'

**Comment by ctroein** [comment]
The source of this bug is that [pymatreader](https://gitlab.com/obob/pymatreader/-/blob/master/pymatreader/pymatreader.py) assumes that scipy.io.loadmat takes an undocumented argument uint16_codec. This works for version 5 files (mio5.py) where init recognizes it, but fails for mio4 files. As as workaround, I've added a call to loadmat in case we get a TypeError from read_mat. (But so far only where the images are loaded.)
